brain-tec assignment/rodriguez_cortes_jose_carlos/models/__init__.py
from . import contact

brain-tec assignment/rodriguez_cortes_jose_carlos/models/contact.py
from rodriguez_cortes_jose_carlos.db import get_db
import defusedxml.ElementTree as et
import re

ID = 0
NAME = 1
LAST_NAME = 2
ADDRESS = 3
EMAIL = 4
PHONE = 5

class Contact:
    def __init__(self, contact_id = None, first_name = None, last_name = None, email = None, phone = None, address = None):
        self.contact_id = contact_id or ""
        self.first_name = first_name or ""
        self.last_name = last_name or ""
        self.email = email or ""
        self.phone = phone or ""
        self.address = address or ""

    # Write this contact to DB
    def write_to_db(self, db = None, cr=None):
        if db == None:
            db = get_db()
        if cr == None:
            cr = db.cursor()

        if not self.contact_exists_in_database(cr=cr):
            cr.execute("USE exercise")
            cr.execute('INSERT INTO contact (firstname, lastname, address, email, phone) VALUES (%s, %s, %s, %s, %s)',
                    (self.first_name, self.last_name, self.address, self.email, self.phone)
            )
            db.commit()
    
    def contact_exists_in_database(self, cr=None):
        if cr == None:
            cr = get_db().cursor()
        cr.execute("USE exercise")
        cr.execute("SELECT * FROM contact WHERE contact_id = %s OR email = %s OR phone = %s",
                    (self.contact_id, self.email, self.phone)
        )
        return len(cr.fetchall()) > 0

    def is_valid_contact(self):
        return self._is_valid_mail() and self._is_valid_phone()

    def _is_valid_mail(self):
        return re.fullmatch(r"^.+@.+\..+$", self.email) != None

    def _is_valid_phone(self):
        return re.fullmatch(r"^\+*[-\s()0-9]+$", self.phone) != None

    def initialize_from_xml(self, xml):
        self.contact_id = 0
        self.first_name = xml.find("firstname").text
        self.last_name = xml.find("lastname").text
        self.email = xml.find("email").text
        self.phone = xml.find("phone").text
        self.address = xml.find("address").text

# Gets all the database contacts
def get_database_contacts():
    db = get_db()
    cr = db.cursor()
    cr.execute("USE exercise")
    cr.execute("SELECT * FROM contact")
    db_contacts = cr.fetchall()
    return [Contact(c[ID], c[NAME], c[LAST_NAME], c[EMAIL], c[PHONE], c[ADDRESS]) for c in db_contacts]

# Returns an array of contacts loaded from a XML file.
# If a contact is in bad format the function doesn't load anything.
# If it's impossible to load anything the function returns a void array "[]"
def load_xml_contact(xml_file):
    contacts = []
    xml_file = "<root>" + xml_file + "</root>"
    root = et.fromstring(xml_file)
    aux_contact = Contact()

    for contact_xml in root:
        aux_contact.initialize_from_xml(contact_xml)
        if aux_contact.is_valid_contact():
            contacts.append(aux_contact)
    return contacts

brain-tec assignment/rodriguez_cortes_jose_carlos/__init__.py
import os
from flask import Flask

from . import db
from . import controllers
from . import models

def create_app(test_config=None):
    # create and configure the app
    app = Flask(__name__)

    if test_config:
        app.config.from_pyfile('test_config.py')
    else: 
        app.config.from_pyfile('config.py')
        
    db.init_app(app)
    app.register_blueprint(controllers.contact.blueprint)
    app.register_blueprint(controllers.uploader.xml_blueprint)
    return app

brain-tec assignment/rodriguez_cortes_jose_carlos/controllers/__init__.py
from . import contact
from . import uploader

brain-tec assignment/rodriguez_cortes_jose_carlos/controllers/contact.py
from flask import (
    Blueprint, flash, redirect, render_template, request, url_for
)

from rodriguez_cortes_jose_carlos.models.contact import Contact, get_database_contacts
from rodriguez_cortes_jose_carlos.db import get_db

blueprint = Blueprint('contacts', __name__, url_prefix="/")

@blueprint.route('/', methods=('GET', 'POST'))
def contact_form():
    if request.method == 'POST':
        contact = Contact(
            None,
            request.form['firstname'],
            request.form['lastname'],
            request.form['email'],
            request.form['phone'],
            request.form['address']
        )
        
        if contact.is_valid_contact():
            contact.write_to_db()
            return redirect(url_for('contacts.contact_list'))
        else:
            flash("You've made some mistake introducing the contact data.")

    return render_template('contact/contact_form.html')

@blueprint.route('/list', methods=('GET', 'POST'))
def contact_list():
    return render_template('contact/contact_list.html', contacts = get_database_contacts())

brain-tec assignment/rodriguez_cortes_jose_carlos/controllers/uploader.py
from rodriguez_cortes_jose_carlos.models.contact import load_xml_contact
from rodriguez_cortes_jose_carlos.db import get_db

from flask import (
    Blueprint, redirect, request, url_for
)

xml_blueprint = Blueprint('upload_xml', __name__, url_prefix="/upload_xml")

ALLOWED_EXTENSIONS = { 'xml' }

def allowed_file(filename):
    return "." in filename and filename.split('.')[1].lower() in ALLOWED_EXTENSIONS

@xml_blueprint.route('/upload_xml', methods=('GET', 'POST'))
def upload_xml():
    if request.method == "POST":
        db = get_db()
        cr = db.cursor()
        file = request.files['xml_file']
        if allowed_file(file.filename):
            xml_text = file.read().decode('utf8')
            for contact in load_xml_contact(xml_text):
                contact.write_to_db(db = db, cr = cr)
        else:
            return redirect(url_for('contacts.contact_form'))

    return redirect(url_for('contacts.contact_list'))

brain-tec assignment/rodriguez_cortes_jose_carlos/templates/base.html
<!DOCTYPE html>
<html lang="es">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css"
        integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
        
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>

    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>

    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"
        integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV"
        crossorigin="anonymous"></script>
    
    {% block header %}{% endblock %}

    <title>BRAIN-TEC ASSIGNEMENT - {% block title %}{% endblock %}</title>
</head>

<body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <a class="navbar-brand" href="{{ url_for('contacts.contact_form') }}">brain-tec Assignement</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
            aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item {% block selected_create %}{% endblock %}">
                    <a class="nav-link" href="{{ url_for('contacts.contact_form') }}">Create Contact </a>
                </li> 
                <li class="nav-item">
                    <a class="nav-link {% block selected_list %}{% endblock %}" href="{{ url_for('contacts.contact_list') }}">Contact List </a>
                </li>
            </ul>
        </div>
    </nav>

    <section class="content">
        {% block content %}{% endblock %}
    </section>
</body>
</html>

brain-tec assignment/rodriguez_cortes_jose_carlos/templates/contact/contact_form.html
{% extends 'base.html' %}
{% block title %}Create Contact{% endblock %}
{% block selected_create %}active{% endblock %}
{% block header %}
{% endblock %}

{% block content %}
<div class="container">
    <div class="row">
        <h1>Create Contact Form</h1>
    </div>
    <div class="row">
        <form method="post">
            <!-- Name -->
            <div class="form-group">
                <label for="firstname">First Name</label>
                <input class="form-control" name="firstname" id="firstname" placeholder="E.g.: Agapito" size="100"
                    required>
            </div>

            <!-- Last Name -->
            <div class="form-group">
                <label for="lastname">Last Name</label>
                <input class="form-control" name="lastname" id="lastname" placeholder="E.g.: Afonso Peña" size="100"
                    required>
            </div>

            <!-- Email -->
            <div class="form-group">
                <label for="email">E-Mail</label>
                <input type="email" class="form-control" name="email" id="email" placeholder="E.g.: test@test.com"
                    pattern="^.+@.+\..+$" size="100" required>
            </div>

            <!-- Phone -->
            <div class="form-group">
                <label for="phone">Phone Number</label>
                <input type="tel" class="form-control" name="phone" id="phone" placeholder="E.g.: 666999666"
                    pattern="^\+*[-\s()0-9]+$" size="30">
            </div>

            <!-- Address -->
            <div class="form-group">
                <label for="address">Address</label>
                <input class="form-control" name="address" id="address" placeholder="E.g.: C\Cheesecake, Nº 42"
                    size="200">
            </div>
            <div>
                <input id="input_button" type="submit" value="Submit" class="btn btn-primary" disabled>
                <small id="message_correct_data" class="invisible">All data is correct.</small>

            </div>
        </form>
    </div>

    <div class="row">
        <h1>Create Contact By XML</h1>
    </div>

    <div class="row">
        <form id="xml_form" name="xml_form" action="{{ url_for('upload_xml.upload_xml') }}" method="POST"
            enctype="multipart/form-data">
            <input id="xml_file" type="file" name="xml_file" accept=".xml"/>
        </form>
    </div>
</div>
<script type=text/javascript src="{{url_for('static', filename='js/contact_form.js') }}"></script>
{% endblock %}

brain-tec assignment/rodriguez_cortes_jose_carlos/templates/contact/contact_list.html
{% extends 'base.html' %}
{% block title %}Contact List{% endblock %}
{% block selected_list %}active{% endblock %}

{% block content %}
<div class="container">
    <div class="row">
        <h1>Contact List</h1>
    </div>
    <div class="row">
        <table class="table">
            <thead>
                <tr>
                    <th scope="col">#</th>
                    <th scope="col">First Name</th>
                    <th scope="col">Last Name</th>
                    <th scope="col">E-Mail</th>
                    <th scope="col">Phone</th>
                    <th scope="col">Address</th>
                </tr>
            </thead>
            <tbody>
                {% for contact in contacts %}
                    <tr>
                        <td>{{ contact.contact_id }}</td>
                        <td>{{ contact.first_name }}</td>
                        <td>{{ contact.last_name }}</td>
                        <td>{{ contact.email }}</td>
                        <td>{{ contact.phone }}</td>
                        <td>{{ contact.address }}</td>
                    </tr>
                {% endfor %}
            </tbody>
        </table>
        
    </div>
</div>


{% endblock %}